drop table Person if exists;
drop table Address if exists;
drop table GeneratedAlways if exists;

create table Person (
   id int not null,
   first_name varchar(30) not null,
   last_name varchar(30) not null,
   birth_date date not null,
   employed varchar(3) not null,
   occupation varchar(30) null,
   address_id int not null,
   parent_id int null,
   primary key(id)
);

create table Address (
   id int not null,
   street_address varchar(30) not null,
   city varchar(30) not null,
   state char(2) not null,
   primary key(id)
);

create table GeneratedAlways (
   id int generated by default as identity(start with 22),
   first_name varchar(30) not null,
   last_name varchar(30) not null,
   full_name varchar(61) generated always as (first_name || ' ' || last_name),
   primary key(id)
);

insert into Address values(1, '123 Main Street', 'Bedrock', 'IN');
insert into Address values(2, '456 Main Street', 'Bedrock', 'IN');

insert into Person values(1, 'Fred', 'Flintstone', '1935-02-01', 'Yes', 'Brontosaurus Operator', 1, null);
insert into Person values(2, 'Wilma', 'Flintstone', '1940-02-01', 'Yes', 'Accountant', 1, null);
insert into Person(id, first_name, last_name, birth_date, employed, address_id, parent_id) values(3, 'Pebbles', 'Flintstone', '1960-05-06', 'No', 1, 2);
insert into Person values(4, 'Barney', 'Rubble', '1937-02-01', 'Yes', 'Brontosaurus Operator', 2, null);
insert into Person values(5, 'Betty', 'Rubble', '1943-02-01', 'Yes', 'Engineer', 2, null);
insert into Person(id, first_name, last_name, birth_date, employed, address_id, parent_id) values(6, 'Bamm Bamm', 'Rubble', '1963-07-08', 'No', 2, 4);

insert into GeneratedAlways(first_name, last_name) values('Fred', 'Flintstone');
insert into GeneratedAlways(first_name, last_name) values('Wilma', 'Flintstone');
insert into GeneratedAlways(first_name, last_name) values('Barney', 'Rubble');
insert into GeneratedAlways(first_name, last_name) values('Betty', 'Rubble');

CREATE TABLE promotion (
   id int,
   created_at date,
   updated_at date,
   applicable_plan_types varchar(255),
   deactivate_reason varchar(255),
   end_date_time date,
   start_date_time date,
   issued_count int,
   registered_count int,
   remain_count int,
   is_activated varchar(1),
   memo varchar(255),
   name varchar(255),
   prefix_code varchar(255),
   is_expired varchar(1)
)
;

insert into promotion values(
    1,
    '1935-02-01',
    '1945-02-01',
    'A,B',
    'deactivate_reason',
    '1945-02-01',
    '1945-02-01',
    1,
    2,
    3,
    'Y',
    'memo',
    'name',
    'prefix_code',
    'N'
)
;
